name: Unit Tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        architecture: ["x64"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements-dev.txt
    - name: Test with pytest and get the coverage
      if: matrix.python-version == 3.10
      run: |
        pytest --cov-report=xml --cov=dot tests/ --runslow
    - name: Test with pytest and no coverage report
      if: matrix.python-version != 3.10
      run: |
        pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.python-version == 3.10
      with:
        file: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
